DOCKER_MACHINE: localhost

cluster:
  trino: ${DOCKER_MACHINE}
  ssh: ${DOCKER_MACHINE}

databases:
  default:
    alias: trino

  trino:
    jdbc_driver_class: io.trino.jdbc.TrinoDriver
    jdbc_url: jdbc:trino://${cluster.trino}:8080/hive/default
    jdbc_user: hdfs

ssh:
  identity: ${IDENTITY}
  roles:
    host_by_password:
      host: ${cluster.ssh}
      password: ${USER_A_PASSWORD}

    host_by_identity:
      host: ${cluster.ssh}
